### ISSUE TITLE
Nit: cosmetics after quit

### ISSUE THREAD

**Issue by grahamperrin** [poetaman/arttime#18]
With https://github.com/reportaman/arttime/commit/34633fce53c44adbe29bf86c6aa53ac7b73a1112 on branch `oldbsdtput':

> `Do you really want to quit arttime? [y/n]: yfreebsd@freebsd:~/dev/arttime $     `

Is it possible to have a clear command line prompt after quit? 

(I have no idea.)

**Comment by reportaman** [comment]
This is indicative that termcap for TERM that you used (my guess is xterm-256color) is stale and does not have alternate screen support smcup(te),rmcup(ti). To confirm export TERM=tmux-256color and then start arttime. This time it  will close with cleaned up look as arttime ran in alternate screen. You will most likely also see 2 lines saying no wrap enable/disable capability smam(SA),rmam(RA) is not found. Both of these are indicative of fact that xterm-256color as well as tmux-256color are suggesting your terminal lacks the capabilities it actually has: alternate screen, enabling/disabling wrap. My observation from forums like for vim is that developers hack their apps by hard coding the escape sequence for such capabilities in their app instead of opening a ticket on someone to update termcap database, as there is no central maintainer across OSes I guess.

Please try and let me know. I can send you hand edits to termcap file but as I mention, I don't know how to generate termcap.db from it. Couldn't find that information online. It would be good for FreeBSD release to have patched termcap that matches the capabilities of its default terminfo expectations.

**Comment by reportaman** [comment]
@grahamperrin I described the same issue in note of https://github.com/reportaman/arttime/issues/16#issuecomment-1263280574. The reason you didn't see terminal capability errors while testing with my fix for  https://github.com/reportaman/arttime/issues/16 is because of missing smcup(te),rmcup(ti) in your xterm-256color termcap.  Those error messages got overwritten when arttime was exiting, this can never happen if terminal supports alternate screen (which yours does but your termcap says it doesn't). That's because arttime would run in alternate screen, not affecting the contents of main screen. It won't happen with tmux-256color... Let's continue the discussion here on what can be done so other developers and users time is not wasted by chasing stale termcaps/terminfo problems. Unlike other developers I don't find value in pushing the problem elsewhere by hacking around user's database by embedding some sequences that work for some terminals. The whole idea of having a termcap/info database is that developers should not embed escape special  sequences in their applications.

**Comment by reportaman** [comment]
@grahamperrin Update: Here's are the steps to correct your termcap database on FreeBSD13.1-RELEASE:

1. cd to ``/usr/share/misc``
2. Make a backup of file named ``termcap`` and ``termcap.db`` under that directory.
3. chmod +w ``termcap`` && chmod +w ``termcap.db``.
4. Open file ``termcap`` in editor of choice.
5. Search line's starting with ``xterm-256color`` and ``tmux-256color`` to find their respective entries in the file, and replace their entry with update capabilities:
```
xterm-256color|xterm alias 3:\
        :Co#256:pa#32767:\
        :AB=\E[48;5;%dm:AF=\E[38;5;%dm:te=\E[?1049l:ti=\E[?1049h:SA=\E[?7h:RA=\E[?7l:tc=xterm-new:
```
```
tmux-256color|tmux with 256 colors:\
        :so=\E[7m:se=\E[27m:te=\E[?1049l:ti=\E[?1049h:SA=\E[?7h:RA=\E[?7l:\
        :tc=ecma+italics:tc=screen-256color:
```
6. Run  ``$ cap_mkdb termcap``. It will regenerate new termcap.db in the same directory.
7. Start another shell and run arttime again, everything will work correctly!!!

As an additional step, open a pull request on FreeBSD for most up-to-date termcap. Not sure if there is a reliable way to generate that from @ThomasDickey's latest terminfo database.

**Comment by grahamperrin** [comment]
> … to correct your termcap database on FreeBSD 13.1-RELEASE: …

It's not my everyday system (I have a few virtual machines running RELEASE versions of the OS). 

My everyday system is 14.0-CURRENT, will steps be the same? 

> … a pull request on FreeBSD …

[Codeberg, GitHub and GitLab mirrors](https://docs.freebsd.org/en/books/handbook/mirrors/#external-mirrors) exist, but not for PR purposes for `src`. 

Instead, we have Phabricator at <https://reviews.freebsd.org/>, with associated use of Bugzilla 5.0.4 at <https://bugs.freebsd.org/>. 

----

I was vaguely aware of various _terminfo_-related commits last year <https://cgit.freebsd.org/src/log/?qt=grep&q=terminfo>, generally I'm out of my depth with things such as termcap and terminfo.

**Comment by poetaman** [comment]
@grahamperrin I have a 14.0-CURRENT VM, and I never got any errors on it. AFAIK they already moved to terminfos instead of termcaps, so you might not get any errors out of the box. If you do, please let me know.

Steps for termcap database is the same on 14.0-CURRENT. Though if your system uses terminfo by default then you might not hit such errors in first place. A hack to test if your shell is using termcap or terminfo is to run this ``$ tset -S -`` command. If the shell is using terminfo, it will return error ``tset: The -S option is not supported under terminfo.``, and if it is using termcap then it will print the entire termcap entry for your ``$TERM``.

Steps for terminfo database are not the same. It would be series of commands using ``infocmp`` and ``tic``. I can post the steps here if you encounter any problem.

If I get time next week I'll try their bug reporting system. Thanks!

**Comment by grahamperrin** [comment]
Thanks. 

14.0-CURRENT, I seem to get: 

`Do you really want to quit arttime? [y/n]: y%`

– **only if** run without a desktop environment, e.g. at `ttyv4`. I don't imagine people running arttime in this context :-) in other words, not an issue. 

----

With my preferred DE (KDE Plasma), there's no cosmetic issue after quit. I'm back to the command prompt, with no remnant of arttime, for example: 

```text
% date ; uname -aKU
Sun  2 Oct 2022 16:56:54 BST
FreeBSD mowa219-gjp4-8570p-freebsd 14.0-CURRENT FreeBSD 14.0-CURRENT #21 main-n258027-c9baa974717a: Fri Sep 16 15:41:27 BST 2022     grahamperrin@mowa219-gjp4-8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG amd64 1400067 1400067
% echo $PAGER
PAGER: Undefined variable.
% echo $0
/bin/tcsh
% which arttime
/home/grahamperrin/.local/bin/arttime
% arttime
% 
```

**Comment by poetaman** [comment]
@grahamperrin Thanks for further reports. I installed a fresh 14.0-CURRENT and noticed that in the terminal that opens after fresh install from grub is not fully featured: 
* The terminfos it comes with are stale too, I had to do ``pkg install terminfo-db`` to get the latest terminfos. Then logging in again does point to new terminfos.
* But the terminal pretending to be xterm, lacks support for alternate screen capability: smcup(ti)/rmcup(te). You can see this by opening a file in vi or vim and closing it. You will notice that contents of the closed file remain on the screen. This does not happen with vi/vim on terminal that does support alternate screen.

While this application is intended to be used mostly on one's daily driver DE, it is also intended to work perfectly well in a tty. Though the terminal running that tty should support basic features like alternate screen. You can test this by SSHing into your FreeBSD 14.0 machine from another machine's DE. You shouldn't see the problem of arttime or vi/vim leaving any characters painted on the ssh tty. If you do, try ssh login again with ``pkg install terminfo-db`` or its equivalent on both 14.0-CURRENT machines.

The reason the prompt looks more annoying after arttime exits on such environment is perhaps because vim exits right after emitting a newline character. Maybe that's what I should do too. That way people get a equally good experience as exiting from vim on such limited terminals.

I will also try to push a better error reporting mechanism today so error won't be overwritten on terminals that do not support alternate screen.

**Comment by poetaman** [comment]
@grahamperrin Pull and give it a try again, as explained above comment, arttime will imitate vim's exit strategy on environment with limited term capabilities or inaccurate terminfos. In short you should see a clean prompt each time you exit arttime.

**Comment by grahamperrin** [comment]
<https://github.com/poetaman/arttime/issues/18#issuecomment-1264675619> no longer reproducible. 

Thanks!
