### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by notjedi** [poetaman/arttime#5]
please submit a `PKGBUILD` to the Arch User Repository if possible.

**Comment by reportaman** [comment]
@notjedi Contributions are welcome, I wouldn't know how to do that. Would you like to contribute to AUR?

**Comment by Deckweiss** [comment]
I've added it to the AUR https://aur.archlinux.org/packages/arttime-git

Would be nice if somebody can confirm whether everything works as expected, since I never used the program before and only checked if it starts. 

@poetaman `myapp-git` AUR packages are meant to be rebuild by the user when they want. It automatically fetches the latest git main branch state. A non -git version that is synced with your releases can be added either by somebody else, or (more meaningfully) it can be done through github actions (I can help you with that if you want, let me know)

**Comment by poetaman** [comment]
@Deckweiss Thanks! I am traveling today, will be able to test it tomorrow. I wouldn't know anything about AUR, its systems you talk about. It would be nice to have the GitHub actions system you talk about. So far I have been keeping the main branch clean, though we can add the GitHub action if you see value in it and feel motivated.

**Comment by notjedi** [comment]
i tried downloading the package from AUR, seems to work fine for me.

**Comment by poetaman** [comment]
@Deckweiss Works, though might need two updates. Arttime has some recommended dependencies to be installed:

1. ``zsh`` >= 5.7
2. ``extra/libnotify`` for desktop notifications
3. ``core/less`` for navigation of help pages (default more is less powerful)
4. ``core/diffutils`` for systems where /etc/localtime is not a symlink and arttime needs to guess the timezone.
5. ``extra/vorbis-tools`` for sounds in case user has not installed pulseaudio or pipwire. arttime cares about paplay command, not the underlying daemon. If paplay is not found, it does a fallback on ``ogg123`` of ``vorbis-tools``. Not sure if the pkgbuild can be conditional and would allow conditional installation: if paplay is found then don't install vorbis-tools.

**Comment by Deckweiss** [comment]
@poetaman thank you, will fix later!

**Comment by Deckweiss** [comment]
@poetaman

- I've added the version to the `zsh` dependency
- Added `libnotify`, `diffutils` and `vorbis-tools` as optional dependencies with a description of what they are needed for, so the user can decide themselves whether to install them.
- `less` comes preinstalled on arch (as dependency of the `base` package)

There is already a link to your github home page, so I have left it out of the description.

___

just fyi, the reasoning on why I decided to package it the way I did.

I tried to use your installer to install everything to the arch recommended paths. `./install.sh -p /usr/share/ --zcompdir /usr/share/zsh/site-functions`

But decided to circumvent it for now, as it modified the users .bashrc / .zshrc file.
AUR packages should generally not modify anything in the users home.
Additionally as it is, the PATH export is broken due to the install process of AUR packages:

A package first gets "installed" to a temporary directory, then packaged as a `.pkg` file and then installed the same as any other arch package. 

```
# Following line was automatically added by arttime installer
export PATH=/home/deckweiss/Projects/arttime-git-AUR/pkg/arttime-git/usr/local//bin:$PATH
```

Additionally I have found that there is a hardcoded relational path in the arttime "binary"
`exec zsh -fi ${0:a:h}/../share/arttime/src/arttime.zsh "$@"`

The outcome for anybody that needs to have an overview in the future:

```
usr
├── local
│   ├── bin
│   │   ├── artprint
│   │   └── arttime
│   └── share
│       └── arttime
│           ├── keypoems
│           ├── src
│           └── textart
└── share
    └── zsh
        └── site-functions
            ├── _artprint
            └── _arttime
```

**Comment by poetaman** [comment]
@Deckweiss Thanks! A few observations/questions:

1. Is there a reason why the zsh version you selected is >=5.8 instead of >=5.7?
2. Is there a way to prompt the user to install those dependencies instead of just printing them at the end? My concern is that people are going to miss it as the installer as the return message is 0. Or perhaps we can be more conservative for smaller dependencies...
3. Is there a reason why ``/usr/share`` for zsh completions vs ``/usr/local/share`` for arttime? On both of my Mac and Arch Linux machines ``zsh -dfi -c 'printf "%s\n" "$fpath[@]"'`` has ``/usr/local/sharez/zsh/site-functions/`` by default in  fpath.

Description looks good now :)

Yes, the hardcoded relational path was a recent change. As you would know there is no POSIX complaint way to pass options to an interpreter launched by ``/usr/bin/env`` (as env considers all that follows as single word). There is a non-standard ``-S`` option in recent GNU coreutils and in BSD (which serves macOS too), but it is non-standard. At first I considered adding ``arttime.zsh`` to the same bin directory (without ``chmod +x``), but zsh completion framework on one of my machine completes all files in bin directory irrespective of whether they are executable or not. That would have led to confusion for users who use less completion frameworks. Also unfortunately, zsh does not allow shell to become interactive after it has been launched, so at least ``-i`` needs to be passed at launch time.

**Comment by Deckweiss** [comment]
@poetaman Thanks for the feedback

1. I was sleepy and mistyped, good catch! Will fix.
2. AUR users are expected to read the PKGBUILD file before installing, but even if they do not, many of the AUR helper utilities either show or prompt the optional dependencies. I think it makes sense to have the dependencies as optional for the following reasons:
- `diffutils` might be entirely unnecessary on arch if the only reason is to guess the timezone. `/etc/localtime` should be always present. I've decided to leave it in just in case somebody intentionally removed the timezone for some reason.
- `vorbis-tools`  most desktop users would have pulse or pipewire installed.
- `libnotify` some people prefer to not have notifications.
- In all cases, I think arch users often prefer to have no 'bloat' and rather consciously configure the minimal set of optional depenencies that covers their specific needs.
3. `/usr/local/share/zsh/site-functions` is in the fpath, but it does not exist on my arch system. Instead all installed programs seem to have their autocompletions in `/usr/share/zsh/site-functions` so it seemed to fit there better even if the other path would have worked as well. 

Ah! I didn't consider the passing of the arguments for the launch. A way to work around it would be to modify the `bin` file post install. But it is no big deal anyway as far as I understand.

**Comment by poetaman** [comment]
@Deckweiss Awesome, thanks!

Now we can perhaps celebrate this by adding a Linux mascot Tux to arttime's repository. If you would like to be in the contributors list, feel free to open a PR with a file named ``linux`` or ``linuxtux`` with following exact contents in directory [share/arttime/textart](https://github.com/poetaman/arttime/tree/main/share/arttime/textart).
```
"Custom message for art goes here"
            a8888b.   
           d888888b. 
           8P"YP"Y88 
           8|o||o|88 
           8'    .88 
           8`._.' Y8. 
          d/      `8b. 
         dP   .    Y8b. 
        d8:'  "  `::88b 
       d8"         'Y88b 
      :8P    '      :888 
       8a.   :     _a88P 
     ._/"Yaa_:   .| 88P| 
jgs  \    YP"    `| 8P  `.
a:f  /     \.___.d|    .' 
     `--..__)8888P`._.' 
```
