### ISSUE TITLE
[Question] Is it possible to automatically cycle through art every X seconds?

### ISSUE THREAD

**Issue by continue47** [poetaman/arttime#61]
I have an old crt that I would like to use to display random ASCII art, I hooked it up to a raspberry pi and while I found that I can start arttime with --random I couldn't figure out a way to make it automatically change the art at a specific interval.

I ended up writing a python script to kind of do this - just reads from the arttime directory where the actual ascii files are stored and refreshes at an interval - but it's not ideal since it doesn't nicely center them as arttime. 

Is there a way to achieve something like this with arttime?

Thanks.

**Comment by poetaman** [comment]
@continue47 There are two ways you can achieve this: 1) a simple one that wouldn't loop forever but is easy to test, 2) one where you can loop forever, the UI can be improved a bit.

1) Create a keypoem file with name like ``randomart_Xs`` (``randomart_1s`` 1s stands for read rate of 1 byte/second), and put as long a sequence of js: ``jjjjjjjjjjj...y`` or ``jjjjjjjjjjj...n``. Then start arttime like this:

```
arttime --nolearn -k /path/to/randomart_1s
```

The cycling would end when the last character is encountered (``n`` is optional as EOF cancels the selection anyway). So, if you want to cycle for 1 hour, the file would have 3600 js. For people who can code... 2nd technique is more appealing:

2) Write a python program that creates a named pipe like ``randomartfifo`` (name can be anything) and write as many js in a loop, and pass that named pipe to arttime instead of file (like below). The general specification for writing such programs is in the CONTRIBUTING. Here's a link:

```
arttime --nolearn -k /path/to/randomartfifo
```

Don't end the name with _Xs (you can but don't), and control the delays from python to insert even random delays if you want...

Pressing Ctrl-c (or equivalent interrupt keybinding for your computer) ends SCRIPT mode of arttime, and the control will be transferred to your computer again. You can restart the cycle again from within arttime by pressing k, and then passing the path to same file/fifo. I would recommended reading the section ORCHESTRATING too and seeing a GIF in the release notes that shows how arttime can be used to display dynamic information from external feeder programs (weather data in this case): https://github.com/poetaman/arttime/releases/tag/v2.3.0

**Comment by continue47** [comment]
I took your advice and used artprint --random from python. It has all the options I needed including setting the colors for the art and title, centering the art, and setting a max width, great stuff!

Thank you for such a detailed reply!

**Comment by poetaman** [comment]
@continue47 You are welcome! Please feel free to share an image or video of your raspberry-pi + CRT + arttime setup. If it's a nice shot, I might consider pinning it in the wiki.

**Comment by poetaman** [comment]
@continue47 You might want to update to the latest commit. It should be visibly faster on slow machines like raspberry pi.
