### ISSUE TITLE
Web Version

### ISSUE THREAD

**Issue by insiwd** [poetaman/arttime#64]
hello! i love arttime. is there a plan to a web version? i would love it

**Comment by poetaman** [comment]
@insiwd Curious what was the rationale for the web version? Did you mean it would run in the browser? What use case was in your mind? Anyway, thanks for liking arttime and your interest.

**Comment by insiwd** [comment]
@poetaman Hello, I love this project. The idea was that, running in my browser, I could easily use artttime on other computers/phones. I can't find any website/app with this aesthetic and simplicity. I closed the issue because I understood that it's not part of the concept behind the project

**Comment by poetaman** [comment]
@insiwd Got it, thanks for elaborating! Yes, you understood it right. Thanks!

**Comment by Dhyfer1** [comment]
I'd also like to see it in a web version since there's no support for Windows. :(

**Comment by poetaman** [comment]
@Dhyfer1 There is Windows support in the form of WSL, for more info please check https://github.com/poetaman/arttime/issues/53#issuecomment-1548397639. Since I don't have a Windows machine to test, I can't speak much whether it still works well (as notifications require installing another package).

If by web you mean in your browser, then I guess one way to get this to work is some kind of browser based terminal. For that you might want to search "web ssh" and sshing to your local machine from the browser and running arttime from the virtual ssh terminal in the browser. Please let us know your feedback about this method if you ever get a chance to try. Thanks!
